name: Deploy to lambda

on:
  push:
    branches:
    - master

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: npm install
        env:
          CI: true
        run: |
          npm ci
      - name: deploy
        run: |
          zip -9 -r deploy.zip resolvers index.js package.json serverless.yml webpack.config.js schema.js package-lock.json
          aws lambda update-function-code --function-name=the-star-wars-api --zip-file=fileb://deploy.zip
